version: '3'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node API service
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      MONGO_URL: mongodb://mongo_db:27017
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}